/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ptv_Reader_NFC_NfcReaderImpl */

#ifndef _Included_com_ptv_Reader_NFC_NfcReaderImpl
#define _Included_com_ptv_Reader_NFC_NfcReaderImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ptv_Reader_NFC_NfcReaderImpl
 * Method:    openNfcDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ptv_Reader_NFC_NfcReaderImpl_openNfcDevice
  (JNIEnv *, jclass);

/*
 * Class:     com_ptv_Reader_NFC_NfcReaderImpl
 * Method:    closeNfcDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ptv_Reader_NFC_NfcReaderImpl_closeNfcDevice
  (JNIEnv *, jclass);

/*
 * Class:     com_ptv_Reader_NFC_NfcReaderImpl
 * Method:    getDeviceName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ptv_Reader_NFC_NfcReaderImpl_getDeviceName
  (JNIEnv *, jclass);

/*
 * Class:     com_ptv_Reader_NFC_NfcReaderImpl
 * Method:    startPolling
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ptv_Reader_NFC_NfcReaderImpl_startPolling
  (JNIEnv *, jclass);

/*
 * Class:     com_ptv_Reader_NFC_NfcReaderImpl
 * Method:    stopPolling
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ptv_Reader_NFC_NfcReaderImpl_stopPolling
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
