/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ptv_JNI_Cpp_example */

#ifndef _Included_com_ptv_JNI_Cpp_example
#define _Included_com_ptv_JNI_Cpp_example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ptv_JNI_Cpp_example
 * Method:    helloVis
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ptv_JNI_Cpp_1example_helloVis
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
